name: Deploy Next.js to Cloudways

on:
    push:
        branches:
            - pre-prod # This will only trigger deployment for the main branch

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20" # Use the appropriate Node.js version

            - name: Install dependencies
              run: npm install

            - name: Build the Next.js app
              run: npm run build

            - name: SSH Deploy # Use the 'appleboy/ssh-action' action for SSH deployment
              uses: appleboy/ssh-action@v3
              with:
                  # host: ${{ secrets.167.71.237.196 }} # Your server's IP address
                  # username: ${{ secrets.nagadhat-v3-frontend }} # Your server's username
                  # key: ${{ secrets.AAAAB3NzaC1yc2EAAAADAQABAAACAQDIjixk0GjYIRtUf11jxjgyGIHH5IpElErGp3UXbKLGqGXVBrlDel+RfkC+mBM }} # Your server's SSH private key
                  script: |
                      cd cd ./public_html # Specify the path to your app directory on the server
                      git pull
                      npm install
                      npm run build
                      pm2 restart nagadhat-v3-frontend # Replace with your PM2 service name
